common:
  model: ogb_originalgin
  dropout: 0.0
  hid_size: 32
  lr: 1.e-3
  lr_steps: [ 200, 300, 400 ]
  patience: 100
  reg: 0.
  num_convlayers: 6
  batch_size: 32
  min_epochs: 300
  max_epochs: 500
  data_path: './datasets'
  debug: False
  num_runs: 5