fixed:
  dataset: zinc
  log_path: './logs'
  voting: 5

  sample_configs:
    sample_policy: node
    sample_k: 5
    num_subgraphs: 10
    remove_node: True
    add_full_graph: False
    sample_with_esan: False

  imle_configs: null
