fixed:
  dataset: ogbg-molesol
  log_path: './logs'
  voting: 1

  sample_configs:
    sample_policy: node
    sample_k: 10
    num_subgraphs: 10
    remove_node: True
    add_full_graph: True
    sample_with_esan: False

  imle_configs: null
